# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            CRM Docs
tagline:          'CRM Documentation Repository'
description:      'Documentation of CRM functionalities and change requests'
url:              https://github.deutsche-boerse.de/pages/vs535/CRM-Documentation-with-Hyde/
baseurl:          /

author:
  name:           'SAP & Corporate Tools/CRM'
  url:            https://github.deutsche-boerse.de/pages/vs535/CRM-Documentation-with-Hyde/

paginate:         5

layouts_dir         : site/_layouts
includes_dir        : site/_includes

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
# sass:
#  sass_dir:          _sass
#  style:            :compressed

# Custom vars
version:             01.2018
github:
  repo:              https://github.deutsche-boerse.de/vs535/CRM-Documentation-with-Hyde



